language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"

install:
  - curl -s https://raw.githubusercontent.com/go-task/task/master/install-task.sh | sh
  - sudo apt-get install -y dieharder

script:
  - ./bin/task build

after_success:
  - travis_wait 20 sudo dieharder -a -f ./rand/sample.txt

after_script:
  - bash <(curl -s https://codecov.io./bash) -f ./coverage.txt
