language: go
go:
  - "1.8"
  - "1.9"
  - "1.10"
install:
  - curl -s https://raw.githubusercontent.com/go-task/task/master/install-task.sh | sh

script:
  - ./bin/task build

after_success:
  - bash <(curl -s https://codecov.io./bash) -f ./coverage.txt
