codecov:
  notify:
    require_ci_to_pass: yes
coverage:
  precision: 2
  round: down
  range: 10...100
  status:
    project:
      default:
        enabled: yes
        target: "70%"
        threshold: "3%"
    patch: no
    changes: no
comment: off
