version: '2'

tasks:
  build:
    cmds:
      - go build ./rand/
      - gofmt -s -w ./rand/rand.go
      - gofmt -s -w ./rand/rand_test.go
      - go test ./rand/ -coverprofile=coverage.txt -covermode=atomic 
